/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Dashboard: () => import('#controllers/dashboard_controller'),
  Environments: () => import('#controllers/environments_controller'),
  ImageTemplates: () => import('#controllers/image_templates_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
  Users: () => import('#controllers/users_controller'),
}
