/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class EnvironmentLogSchema extends BaseModel {
  static $columns = ['createdAt', 'environmentId', 'id', 'level', 'message'] as const
  $columns = EnvironmentLogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare environmentId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare level: string
  @column()
  declare message: string
}

export class EnvironmentUserSchema extends BaseModel {
  static $columns = ['accessLevel', 'createdAt', 'environmentId', 'id', 'userId'] as const
  $columns = EnvironmentUserSchema.$columns
  @column()
  declare accessLevel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare environmentId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
}

export class EnvironmentSchema extends BaseModel {
  static $columns = ['authPassword', 'authUsername', 'connectionToken', 'containerId', 'containerName', 'cpuLimit', 'createdAt', 'dockerImage', 'errorMessage', 'id', 'imageTemplateId', 'lastAccessedAt', 'memoryLimitMb', 'name', 'ownerId', 'slug', 'status', 'subdomain', 'updatedAt'] as const
  $columns = EnvironmentSchema.$columns
  @column()
  declare authPassword: string
  @column()
  declare authUsername: string
  @column()
  declare connectionToken: string | null
  @column()
  declare containerId: string | null
  @column()
  declare containerName: string | null
  @column()
  declare cpuLimit: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dockerImage: string
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageTemplateId: number | null
  @column.dateTime()
  declare lastAccessedAt: DateTime | null
  @column()
  declare memoryLimitMb: number
  @column()
  declare name: string
  @column()
  declare ownerId: number
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare subdomain: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ImageTemplateSchema extends BaseModel {
  static $columns = ['buildError', 'buildStatus', 'createdAt', 'description', 'dockerImage', 'dockerfile', 'extensions', 'id', 'isBuiltin', 'isDefault', 'lastBuiltAt', 'name', 'slug', 'updatedAt'] as const
  $columns = ImageTemplateSchema.$columns
  @column()
  declare buildError: string | null
  @column()
  declare buildStatus: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare dockerImage: string
  @column()
  declare dockerfile: string | null
  @column()
  declare extensions: any | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isBuiltin: boolean
  @column()
  declare isDefault: boolean
  @column.dateTime()
  declare lastBuiltAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActive', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
